export type DashboardLocale = "zh" | "en";

const copy = {
  zh: {
    metaTitle: "管理后台",
    metaDescription: "管理用户、文章、评论、订单、配置与其他运营模块。",
    shell: {
      eyebrow: "Admin",
      title: "管理后台",
      description: "使用现有 SDK 管理站点核心数据，前后台界面完全隔离。",
      accountEntry: "查看前台账号页",
      noRoleHint:
        "未检测到明确的管理员角色，如果接口返回 403，请先确认账号权限。",
    },
    common: {
      loading: "正在加载后台数据...",
      reload: "重新加载",
      retry: "重试",
      reset: "重置",
      search: "搜索",
      save: "保存",
      cancel: "取消",
      edit: "编辑",
      delete: "删除",
      create: "创建",
      deleteConfirm: "确认删除这条数据吗？",
      audit: "审核",
      auditConfirm: "确认审核这篇文章吗？",
      approve: "通过",
      reject: "拒绝",
      auditReason: "审核原因",
      auditReasonPlaceholder: "输入审核原因（可选）",
      featured: "精华",
      featuredDescription: "开启后，文章会在前台以精华内容展示。",
      filters: "筛选条件",
      queryTable: "查询表格",
      expand: "展开",
      collapse: "收起",
      noFilters: "当前未设置筛选条件",
      pageSize: "每页",
      refresh: "刷新",
      density: "密度",
      columnSetting: "列设置",
      densityDefault: "默认",
      densityMiddle: "中等",
      densitySmall: "紧凑",
      previous: "上一页",
      next: "下一页",
      all: "全部",
      noData: "暂无数据",
      noPermission: "当前账号可能没有后台权限，请确认接口鉴权。",
      page: "第 {page} / {totalPages} 页",
      currentPageCount: "当前页 {count} 条",
      selectPlaceholder: "请选择...",
      upload: "上传",
      replace: "替换",
      passwordPlaceholder: "输入新密码",
    },
    nav: {
      overview: "概览",
      users: "用户",
      articles: "文章",
      comments: "评论",
      points: "积分",
      orders: "订单",
      configs: "配置",
      tags: "标签",
      categories: "分类",
      roles: "角色",
      permissions: "权限",
      banners: "轮播",
      reports: "举报",
      decorations: "装饰品",
      emojis: "表情",
      achievements: "成就",
      search: "搜索",
    },
    pages: {
      overview: {
        title: "站点概览",
        description: "优先看核心总量，再看最近变化，保证后台首页先有管理价值。",
        publicConfig: "公开配置",
        advertisement: "广告配置",
        site: "站点",
        maintenance: "维护模式",
        membership: "会员",
        contact: "联系方式",
        homepageAd: "首页广告",
        articleTopAd: "文章顶部广告",
        articleBottomAd: "文章底部广告",
        globalAd: "全局广告",
        pendingQueue: "待处理订单队列",
        noPendingOrders: "暂无待处理订单号。",
      },
      users: {
        title: "用户管理",
        description: "查看用户账号状态、角色、内容产出与最近活跃时间。",
        fields: {
          password: "密码",
          banReason: "封禁原因",
          address: "地址",
          gender: "性别",
          birthDate: "生日",
          wallet: "钱包余额",
          inviteCode: "邀请码",
          membershipLevel: "会员等级",
          membershipLevelName: "会员等级名称",
          membershipStatus: "会员状态",
          membershipStartDate: "会员开始日期",
          membershipEndDate: "会员结束日期",
        },
        gender: {
          male: "男",
          female: "女",
          other: "其他",
        },
      },
      articles: {
        title: "文章管理",
        description: "检查文章状态、作者归属、浏览互动与最近更新时间。",
      },
      comments: {
        title: "评论管理",
        description: "按关键词巡检评论内容，快速定位文章上下文和作者。",
      },
      points: {
        title: "积分管理",
        description: "管理积分活动、每日任务奖励和启用状态。",
        activityCodes: {
          PUBLISH_ARTICLE: "发布文章",
          LIKE_ARTICLE: "点赞文章",
          PUBLISH_COMMENT: "发表评论",
          LIKE_COMMENT: "点赞评论",
          DAILY_LOGIN: "每日登录",
          ARTICLE_RECEIVED_LIKE: "文章被他人点赞",
          COMMENT_RECEIVED_LIKE: "评论被他人点赞",
          ARTICLE_RECEIVED_COMMENT: "文章被他人评论",
        },
      },
      orders: {
        title: "订单管理",
        description: "追踪订单流水、支付状态和最近交易记录。",
      },
      configs: {
        title: "配置管理",
        description: "查看配置分组、类型与公开状态，确认后台配置项完整性。",
        loadFailedTitle: "配置加载失败",
        loadFailedDescription: "当前配置列表无法从管理接口获取。",
        searchPlaceholder: "搜索配置 key 或描述",
        uploadImage: "上传图片",
        replaceImage: "替换图片",
        removeImage: "移除图片",
        saving: "保存中",
        uploadFailed: "图片上传失败",
        saveFailed: "配置更新失败",
        emptyGroup: "当前分组下暂无配置项。",
        selectedGroupCount: "{count} 项配置",
        typeLabel: "类型",
        updatedLabel: "更新时间",
        imagePreviewAlt: "配置图片",
        create: "新建配置",
        createTitle: "新建配置项",
        editTitle: "编辑配置项",
        deleteConfirm: "确认删除此配置项吗？此操作不可恢复。",
        deleteFailed: "删除失败",
        createFailed: "创建失败",
        keyLabel: "配置 Key",
        keyPlaceholder: "输入唯一的配置 key，如: site.name",
        keyRequired: "配置 Key 不能为空",
        groupLabel: "分组",
        groupPlaceholder: "输入分组名称",
        typeSelectLabel: "数据类型",
        valueLabel: "默认值",
        descriptionLabel: "描述",
        descriptionPlaceholder: "输入配置项的描述说明",
        publicLabel: "公开访问",
      },
      tags: {
        title: "标签管理",
        description: "查看标签基础信息、内容数量和关注热度。",
      },
      categories: {
        title: "分类管理",
        description: "查看分类层级结构、文章数量和排序信息。",
      },
      roles: {
        title: "角色管理",
        description: "查看角色状态、系统角色标记和权限数量。",
      },
      permissions: {
        title: "权限管理",
        description: "查看权限点名称和描述，核对后台权限边界。",
      },
      banners: {
        title: "轮播管理",
        description: "查看轮播图状态、跳转链接和排序信息。",
      },
      reports: {
        title: "举报管理",
        description: "查看举报记录和处理状态，追踪待处理问题。",
      },
      decorations: {
        title: "装饰品管理",
        description: "查看装饰品状态、类型、稀有度和价格信息。",
      },
      emojis: {
        title: "表情管理",
        description: "查看表情状态、分类、使用次数和公开状态。",
      },
      achievements: {
        title: "成就管理",
        description: "查看成就基础信息、类型、稀有度和启用状态。",
        fields: {
          icon: "图标",
          rewardPoints: "奖励积分",
          rewardExp: "奖励经验",
          rewardDecorationId: "奖励装饰品",
          hidden: "隐藏",
          condition: "条件",
          conditionPlaceholder:
            '{\n  "type": "count",\n  "event": "article_publish",\n  "target": 1\n}',
          pointsLabel: "积分",
          expLabel: "经验",
        },
        typeOptions: {
          ARTICLE: "文章",
          COMMENT: "评论",
          SOCIAL: "社交",
          LEVEL: "等级",
          SPECIAL: "特殊",
        },
        rarityOptions: {
          COMMON: "普通",
          RARE: "稀有",
          EPIC: "史诗",
          LEGENDARY: "传说",
        },
      },
      search: {
        title: "搜索管理",
        description: "管理 Elasticsearch 搜索索引、同步状态和热门搜索词。",
        syncArticles: "同步文章索引",
        clearArticles: "清空文章索引",
        syncStatus: "同步状态",
        hotSearch: "热门搜索",
        hotSearchManagement: "热门搜索词管理",
        indexStatus: "索引状态",
        lastSyncTime: "最后同步时间",
        documentCount: "文档数量",
        indexSize: "索引大小",
        syncing: "同步中...",
        syncSuccess: "同步成功",
        syncFailed: "同步失败",
        clearConfirm: "确定要清空所有文章搜索索引吗？此操作不可恢复！",
        clearSuccess: "索引已清空",
      },
    },
    summary: {
      users: "用户总数",
      articles: "文章总数",
      comments: "评论总数",
      orders: "订单总数",
      pendingOrders: "待处理订单",
      configs: "配置项总数",
    },
    sections: {
      latestUsers: "最近用户",
      latestArticles: "最近文章",
      latestComments: "最新评论",
      latestOrders: "最近订单",
      latestConfigs: "配置预览",
      recentChanges: "最近变化",
      moduleShortcuts: "管理模块",
    },
    shortcuts: {
      overview: "查看后台总览和关键统计。",
      users: "搜索用户账号与角色信息。",
      articles: "检查文章状态和内容归属。",
      comments: "巡检评论内容与文章上下文。",
      points: "管理积分活动配置、奖励数值和启用状态。",
      orders: "核对支付状态和订单流水。",
      configs: "查看系统配置和公开项。",
      tags: "查看标签数量、排序和关注热度。",
      categories: "查看分类层级、文章数量和排序。",
      roles: "核对角色状态、系统标记和权限规模。",
      permissions: "检查权限点和描述是否完整。",
      banners: "查看轮播状态、图片和链接配置。",
      reports: "巡检举报记录和处理状态。",
      decorations: "查看装饰品类型、价格和上架状态。",
      emojis: "查看表情分类、使用次数和公开状态。",
      achievements: "查看成就类型、稀有度和启用状态。",
    },
    filters: {
      keyword: "关键词",
      keywordPlaceholder: "输入关键词",
      articleTitlePlaceholder: "输入文章标题",
      commentPlaceholder: "搜索评论内容",
      pointsPlaceholder: "输入活动名称或代码",
      orderPlaceholder: "搜索订单号或标题",
      configPlaceholder: "搜索配置 key 或描述",
      tagNamePlaceholder: "输入标签名称",
      categoryPlaceholder: "输入分类名称",
      roleNamePlaceholder: "输入角色名称",
      bannerTitlePlaceholder: "输入轮播标题",
      reportPlaceholder: "搜索举报原因",
      decorationPlaceholder: "搜索装饰品名称",
      emojiPlaceholder: "搜索表情名称",
      achievementPlaceholder: "搜索成就名称",
      status: "状态",
      group: "分组",
    },
    columns: {
      user: "用户",
      roles: "角色",
      posts: "文章",
      followers: "粉丝",
      updatedAt: "更新时间",
      article: "文章",
      author: "作者",
      category: "分类",
      views: "浏览",
      comments: "评论",
      status: "状态",
      content: "内容",
      sourceArticle: "所属文章",
      likes: "点赞",
      replies: "回复",
      orderNo: "订单号",
      title: "标题",
      type: "类型",
      amount: "金额",
      userId: "用户 ID",
      key: "Key",
      value: "值",
      public: "公开",
      group: "分组",
      name: "名称",
      description: "描述",
      sort: "排序",
      count: "数量",
      system: "系统",
      permissions: "权限数",
      image: "图片",
      link: "链接",
      action: "操作",
      reason: "原因",
      rewardPoints: "奖励积分",
      targetCount: "目标次数",
      dailyLimit: "每日限制",
      totalLimit: "总限制",
      validDays: "有效天数",
      categoryLabel: "分类",
      rarity: "稀有度",
      price: "价格",
      enabled: "启用",
      code: "代码",
    },
    empty: {
      users: "没有匹配的用户。",
      articles: "没有匹配的文章。",
      comments: "没有匹配的评论。",
      orders: "没有匹配的订单。",
      configs: "没有匹配的配置。",
      tags: "没有匹配的标签。",
      categories: "没有匹配的分类。",
      roles: "没有匹配的角色。",
      permissions: "没有权限数据。",
      banners: "没有匹配的轮播。",
      reports: "没有匹配的举报。",
      decorations: "没有匹配的装饰品。",
      emojis: "没有匹配的表情。",
      achievements: "没有匹配的成就。",
    },
    status: {
      DRAFT: "草稿",
      PUBLISHED: "已发布",
      PENDING: "待处理",
      PAID: "已支付",
      CANCELLED: "已取消",
      REFUNDED: "已退款",
      PROCESSING: "处理中",
      RESOLVED: "已解决",
      REJECTED: "已拒绝",
      UNDER_REVIEW: "审核中",
      APPROVED: "已通过",
      active: "启用",
      inactive: "停用",
      deleted: "已删除",
      public: "公开",
      private: "私有",
    },
  },
  en: {
    metaTitle: "Admin Dashboard",
    metaDescription:
      "Manage users, articles, comments, orders, configs, and operational modules.",
    shell: {
      eyebrow: "Admin",
      title: "Dashboard",
      description:
        "Manage core site data through the existing SDK with a dedicated back-office shell.",
      accountEntry: "Open front profile",
      noRoleHint:
        "No explicit admin role was detected. If APIs return 403, verify account permissions.",
    },
    common: {
      loading: "Loading dashboard data...",
      reload: "Reload",
      retry: "Retry",
      reset: "Reset",
      search: "Search",
      save: "Save",
      cancel: "Cancel",
      edit: "Edit",
      delete: "Delete",
      create: "Create",
      deleteConfirm: "Delete this item?",
      audit: "Audit",
      auditConfirm: "Audit this article?",
      approve: "Approve",
      reject: "Reject",
      auditReason: "Audit Reason",
      auditReasonPlaceholder: "Enter audit reason (optional)",
      featured: "Featured",
      featuredDescription:
        "When enabled, the article will be highlighted as featured content on the front end.",
      filters: "Filters",
      queryTable: "Query Table",
      expand: "Expand",
      collapse: "Collapse",
      noFilters: "No filters applied",
      pageSize: "Per page",
      refresh: "Refresh",
      density: "Density",
      columnSetting: "Columns",
      densityDefault: "Default",
      densityMiddle: "Middle",
      densitySmall: "Compact",
      previous: "Previous",
      next: "Next",
      all: "All",
      noData: "No data",
      noPermission:
        "This account may not have back-office permission. Check API authorization.",
      page: "Page {page} / {totalPages}",
      currentPageCount: "{count} items on this page",
      selectPlaceholder: "Select...",
      upload: "Upload",
      replace: "Replace",
      passwordPlaceholder: "Enter new password",
    },
    nav: {
      overview: "Overview",
      users: "Users",
      articles: "Articles",
      comments: "Comments",
      points: "Points",
      orders: "Orders",
      configs: "Configs",
      tags: "Tags",
      categories: "Categories",
      roles: "Roles",
      permissions: "Permissions",
      banners: "Banners",
      reports: "Reports",
      decorations: "Decorations",
      emojis: "Emojis",
      achievements: "Achievements",
      search: "Search",
    },
    pages: {
      overview: {
        title: "Site Overview",
        description:
          "Start with exact counts, then inspect the latest changes across the main management modules.",
        publicConfig: "Public Config",
        advertisement: "Advertisement",
        site: "Site",
        maintenance: "Maintenance",
        membership: "Membership",
        contact: "Contact",
        homepageAd: "Homepage Ad",
        articleTopAd: "Article Top Ad",
        articleBottomAd: "Article Bottom Ad",
        globalAd: "Global Ad",
        pendingQueue: "Pending Queue",
        noPendingOrders: "No pending order numbers.",
      },
      users: {
        title: "User Management",
        description:
          "Review account status, roles, content output, and recent activity.",
        fields: {
          password: "Password",
          banReason: "Ban Reason",
          address: "Address",
          gender: "Gender",
          birthDate: "Birth Date",
          wallet: "Wallet Balance",
          inviteCode: "Invite Code",
          membershipLevel: "Membership Level",
          membershipLevelName: "Membership Level Name",
          membershipStatus: "Membership Status",
          membershipStartDate: "Membership Start Date",
          membershipEndDate: "Membership End Date",
        },
        gender: {
          male: "Male",
          female: "Female",
          other: "Other",
        },
      },
      articles: {
        title: "Article Management",
        description:
          "Inspect article status, author ownership, traffic, and recent updates.",
      },
      comments: {
        title: "Comment Management",
        description:
          "Search comment content and trace each record back to its article context.",
      },
      points: {
        title: "Points Management",
        description:
          "Manage points activities, recurring task rewards, and active states.",
        activityCodes: {
          PUBLISH_ARTICLE: "Publish Article",
          LIKE_ARTICLE: "Like Article",
          PUBLISH_COMMENT: "Publish Comment",
          LIKE_COMMENT: "Like Comment",
          DAILY_LOGIN: "Daily Login",
          ARTICLE_RECEIVED_LIKE: "Article Received Like",
          COMMENT_RECEIVED_LIKE: "Comment Received Like",
          ARTICLE_RECEIVED_COMMENT: "Article Received Comment",
        },
      },
      orders: {
        title: "Order Management",
        description:
          "Track payment state, recent transactions, and operational order flow.",
      },
      configs: {
        title: "Config Management",
        description:
          "Review config groups, value types, and public exposure from one place.",
        loadFailedTitle: "Failed to Load Configs",
        loadFailedDescription: "Could not fetch config list from admin API.",
        searchPlaceholder: "Search config key or description",
        uploadImage: "Upload Image",
        replaceImage: "Replace Image",
        removeImage: "Remove Image",
        saving: "Saving...",
        uploadFailed: "Image upload failed",
        saveFailed: "Config update failed",
        emptyGroup: "No config items in this group.",
        selectedGroupCount: "{count} config items",
        typeLabel: "Type",
        updatedLabel: "Updated",
        imagePreviewAlt: "Config Image",
        create: "Create Config",
        createTitle: "Create Config Item",
        editTitle: "Edit Config Item",
        deleteConfirm: "Are you sure you want to delete this config? This action cannot be undone.",
        deleteFailed: "Delete failed",
        createFailed: "Create failed",
        keyLabel: "Config Key",
        keyPlaceholder: "Enter a unique config key, e.g., site.name",
        keyRequired: "Config key is required",
        groupLabel: "Group",
        groupPlaceholder: "Enter group name",
        typeSelectLabel: "Data Type",
        valueLabel: "Default Value",
        descriptionLabel: "Description",
        descriptionPlaceholder: "Enter description for this config",
        publicLabel: "Public Access",
      },
      tags: {
        title: "Tag Management",
        description: "Review tag basics, content volume, and follow heat.",
      },
      categories: {
        title: "Category Management",
        description: "Review category hierarchy, article counts and sort order.",
      },
      roles: {
        title: "Role Management",
        description: "Review role status, system flags, and permission counts.",
      },
      permissions: {
        title: "Permission Management",
        description:
          "Review permission keys and descriptions for the admin boundary.",
      },
      banners: {
        title: "Banner Management",
        description: "Review banner status, target links, and sort order.",
      },
      reports: {
        title: "Report Management",
        description: "Inspect report records and moderation status.",
      },
      decorations: {
        title: "Decoration Management",
        description: "Review decoration status, type, rarity, and pricing.",
      },
      emojis: {
        title: "Emoji Management",
        description: "Review emoji status, category, usage count and public status.",
      },
      achievements: {
        title: "Achievement Management",
        description:
          "Review achievement basics, type, rarity, and enabled state.",
        fields: {
          icon: "Icon",
          rewardPoints: "Reward Points",
          rewardExp: "Reward Exp",
          rewardDecorationId: "Reward Decoration",
          hidden: "Hidden",
          condition: "Condition",
          conditionPlaceholder:
            '{\n  "type": "count",\n  "event": "article_publish",\n  "target": 1\n}',
          pointsLabel: "Points",
          expLabel: "Exp",
        },
        typeOptions: {
          ARTICLE: "Article",
          COMMENT: "Comment",
          SOCIAL: "Social",
          LEVEL: "Level",
          SPECIAL: "Special",
        },
        rarityOptions: {
          COMMON: "Common",
          RARE: "Rare",
          EPIC: "Epic",
          LEGENDARY: "Legendary",
        },
      },
      search: {
        title: "Search Management",
        description: "Manage Elasticsearch index, sync status and hot search keywords.",
        syncArticles: "Sync Article Index",
        clearArticles: "Clear Article Index",
        syncStatus: "Sync Status",
        hotSearch: "Hot Search",
        hotSearchManagement: "Hot Search Management",
        indexStatus: "Index Status",
        lastSyncTime: "Last Sync Time",
        documentCount: "Document Count",
        indexSize: "Index Size",
        syncing: "Syncing...",
        syncSuccess: "Sync Successful",
        syncFailed: "Sync Failed",
        clearConfirm: "Are you sure you want to clear all article search indexes? This action cannot be undone!",
        clearSuccess: "Index Cleared",
      },
    },
    summary: {
      users: "Total Users",
      articles: "Total Articles",
      comments: "Total Comments",
      orders: "Total Orders",
      pendingOrders: "Pending Orders",
      configs: "Config Entries",
    },
    sections: {
      latestUsers: "Latest Users",
      latestArticles: "Latest Articles",
      latestComments: "Latest Comments",
      latestOrders: "Latest Orders",
      latestConfigs: "Config Preview",
      recentChanges: "Recent Changes",
      moduleShortcuts: "Modules",
    },
    shortcuts: {
      overview: "See top-level counts and recent changes.",
      users: "Search accounts and inspect role assignments.",
      articles: "Review article status and ownership.",
      comments: "Inspect comment content with article context.",
      points: "Manage activity configs, reward values, and active states.",
      orders: "Track payment status and order flow.",
      configs: "Review system configuration entries.",
      tags: "Review tag counts, sorting, and follow heat.",
      categories: "Review category hierarchy, article counts and sort order.",
      roles: "Check role status, system flags, and permission scale.",
      permissions: "Inspect permission points and descriptions.",
      banners: "Review banner status, image, and link settings.",
      reports: "Inspect report records and moderation status.",
      decorations: "Review decoration type, price, and availability.",
      emojis: "Review emoji category, usage count and public status.",
      achievements: "Review achievement type, rarity, and enabled state.",
    },
    filters: {
      keyword: "Keyword",
      keywordPlaceholder: "Enter keyword",
      articleTitlePlaceholder: "Enter article title",
      commentPlaceholder: "Search comment content",
      pointsPlaceholder: "Enter activity name or code",
      orderPlaceholder: "Search order no. or title",
      configPlaceholder: "Search config key or description",
      tagNamePlaceholder: "Enter tag name",
      categoryPlaceholder: "Enter category name",
      roleNamePlaceholder: "Enter role name",
      bannerTitlePlaceholder: "Enter banner title",
      reportPlaceholder: "Search report reason",
      decorationPlaceholder: "Search decoration name",
      emojiPlaceholder: "Search emoji name",
      achievementPlaceholder: "Search achievement name",
      status: "Status",
      group: "Group",
    },
    columns: {
      user: "User",
      roles: "Roles",
      posts: "Articles",
      followers: "Followers",
      updatedAt: "Updated",
      article: "Article",
      author: "Author",
      category: "Category",
      views: "Views",
      comments: "Comments",
      status: "Status",
      content: "Content",
      sourceArticle: "Article",
      likes: "Likes",
      replies: "Replies",
      orderNo: "Order No.",
      title: "Title",
      type: "Type",
      amount: "Amount",
      userId: "User ID",
      key: "Key",
      value: "Value",
      public: "Public",
      group: "Group",
      name: "Name",
      description: "Description",
      sort: "Sort",
      count: "Count",
      system: "System",
      permissions: "Permissions",
      image: "Image",
      link: "Link",
      action: "Action",
      reason: "Reason",
      rewardPoints: "Reward Points",
      targetCount: "Target Count",
      dailyLimit: "Daily Limit",
      totalLimit: "Total Limit",
      validDays: "Valid Days",
      categoryLabel: "Category",
      rarity: "Rarity",
      price: "Price",
      enabled: "Enabled",
      code: "Code",
    },
    empty: {
      users: "No matching users.",
      articles: "No matching articles.",
      comments: "No matching comments.",
      orders: "No matching orders.",
      configs: "No matching configs.",
      tags: "No matching tags.",
      categories: "No matching categories.",
      roles: "No matching roles.",
      permissions: "No permissions found.",
      banners: "No matching banners.",
      reports: "No matching reports.",
      decorations: "No matching decorations.",
      emojis: "No matching emojis.",
      achievements: "No matching achievements.",
    },
    status: {
      DRAFT: "Draft",
      PUBLISHED: "Published",
      PENDING: "Pending",
      PAID: "Paid",
      CANCELLED: "Cancelled",
      REFUNDED: "Refunded",
      PROCESSING: "Processing",
      RESOLVED: "Resolved",
      REJECTED: "Rejected",
      UNDER_REVIEW: "Under Review",
      APPROVED: "Approved",
      active: "Active",
      inactive: "Inactive",
      deleted: "Deleted",
      public: "Public",
      private: "Private",
    },
  },
} as const;

export function getDashboardCopy(locale?: string) {
  return locale === "en" ? copy.en : copy.zh;
}
