export type DashboardLocale = "zh" | "en";

const copy = {
  zh: {
    metaTitle: "管理后台",
    metaDescription: "管理用户、文章、评论、订单、配置与其他运营模块。",
    shell: {
      eyebrow: "Admin",
      title: "管理后台",
      description: "使用现有 SDK 管理站点核心数据，前后台界面完全隔离。",
      accountEntry: "查看前台账号页",
      noRoleHint:
        "未检测到明确的管理员角色，如果接口返回 403，请先确认账号权限。",
    },
    common: {
      loading: "正在加载后台数据...",
      reload: "重新加载",
      retry: "重试",
      reset: "重置",
      search: "搜索",
      save: "保存",
      cancel: "取消",
      edit: "编辑",
      delete: "删除",
      deleteConfirm: "确认删除这条数据吗？",
      audit: "审核",
      auditConfirm: "确认审核这篇文章吗？",
      approve: "通过",
      reject: "拒绝",
      auditReason: "审核原因",
      filters: "筛选条件",
      queryTable: "查询表格",
      expand: "展开",
      collapse: "收起",
      noFilters: "当前未设置筛选条件",
      pageSize: "每页",
      refresh: "刷新",
      density: "密度",
      columnSetting: "列设置",
      densityDefault: "默认",
      densityMiddle: "中等",
      densitySmall: "紧凑",
      previous: "上一页",
      next: "下一页",
      all: "全部",
      noData: "暂无数据",
      noPermission: "当前账号可能没有后台权限，请确认接口鉴权。",
      page: "第 {page} / {totalPages} 页",
      currentPageCount: "当前页 {count} 条",
    },
    nav: {
      overview: "概览",
      users: "用户",
      articles: "文章",
      comments: "评论",
      orders: "订单",
      configs: "配置",
      tags: "标签",
      roles: "角色",
      permissions: "权限",
      banners: "轮播",
      reports: "举报",
      decorations: "装饰品",
      achievements: "成就",
    },
    pages: {
      overview: {
        title: "站点概览",
        description: "优先看核心总量，再看最近变化，保证后台首页先有管理价值。",
      },
      users: {
        title: "用户管理",
        description: "查看用户账号状态、角色、内容产出与最近活跃时间。",
      },
      articles: {
        title: "文章管理",
        description: "检查文章状态、作者归属、浏览互动与最近更新时间。",
      },
      comments: {
        title: "评论管理",
        description: "按关键词巡检评论内容，快速定位文章上下文和作者。",
      },
      orders: {
        title: "订单管理",
        description: "追踪订单流水、支付状态和最近交易记录。",
      },
      configs: {
        title: "配置管理",
        description: "查看配置分组、类型与公开状态，确认后台配置项完整性。",
      },
      tags: {
        title: "标签管理",
        description: "查看标签基础信息、内容数量和关注热度。",
      },
      roles: {
        title: "角色管理",
        description: "查看角色状态、系统角色标记和权限数量。",
      },
      permissions: {
        title: "权限管理",
        description: "查看权限点名称和描述，核对后台权限边界。",
      },
      banners: {
        title: "轮播管理",
        description: "查看轮播图状态、跳转链接和排序信息。",
      },
      reports: {
        title: "举报管理",
        description: "查看举报记录和处理状态，追踪待处理问题。",
      },
      decorations: {
        title: "装饰品管理",
        description: "查看装饰品状态、类型、稀有度和价格信息。",
      },
      achievements: {
        title: "成就管理",
        description: "查看成就基础信息、类型、稀有度和启用状态。",
      },
    },
    summary: {
      users: "用户总数",
      articles: "文章总数",
      comments: "评论总数",
      orders: "订单总数",
      pendingOrders: "待处理订单",
      configs: "配置项总数",
    },
    sections: {
      latestUsers: "最近用户",
      latestArticles: "最近文章",
      latestComments: "最新评论",
      latestOrders: "最近订单",
      latestConfigs: "配置预览",
      recentChanges: "最近变化",
      moduleShortcuts: "管理模块",
    },
    shortcuts: {
      overview: "查看后台总览和关键统计。",
      users: "搜索用户账号与角色信息。",
      articles: "检查文章状态和内容归属。",
      comments: "巡检评论内容与文章上下文。",
      orders: "核对支付状态和订单流水。",
      configs: "查看系统配置和公开项。",
      tags: "查看标签数量、排序和关注热度。",
      roles: "核对角色状态、系统标记和权限规模。",
      permissions: "检查权限点和描述是否完整。",
      banners: "查看轮播状态、图片和链接配置。",
      reports: "巡检举报记录和处理状态。",
      decorations: "查看装饰品类型、价格和上架状态。",
      achievements: "查看成就类型、稀有度和启用状态。",
    },
    filters: {
      keyword: "关键词",
      keywordPlaceholder: "输入关键词",
      articleTitlePlaceholder: "输入文章标题",
      commentPlaceholder: "搜索评论内容",
      orderPlaceholder: "搜索订单号或标题",
      configPlaceholder: "搜索配置 key 或描述",
      tagNamePlaceholder: "输入标签名称",
      roleNamePlaceholder: "输入角色名称",
      bannerTitlePlaceholder: "输入轮播标题",
      reportPlaceholder: "搜索举报原因",
      decorationPlaceholder: "搜索装饰品名称",
      achievementPlaceholder: "搜索成就名称",
      status: "状态",
      group: "分组",
    },
    columns: {
      user: "用户",
      roles: "角色",
      posts: "文章",
      followers: "粉丝",
      updatedAt: "更新时间",
      article: "文章",
      author: "作者",
      category: "分类",
      views: "浏览",
      comments: "评论",
      status: "状态",
      content: "内容",
      sourceArticle: "所属文章",
      likes: "点赞",
      replies: "回复",
      orderNo: "订单号",
      title: "标题",
      type: "类型",
      amount: "金额",
      userId: "用户 ID",
      key: "Key",
      value: "值",
      public: "公开",
      group: "分组",
      name: "名称",
      description: "描述",
      sort: "排序",
      count: "数量",
      system: "系统",
      permissions: "权限数",
      image: "图片",
      link: "链接",
      action: "操作",
      reason: "原因",
      categoryLabel: "分类",
      rarity: "稀有度",
      price: "价格",
      enabled: "启用",
      code: "代码",
    },
    empty: {
      users: "没有匹配的用户。",
      articles: "没有匹配的文章。",
      comments: "没有匹配的评论。",
      orders: "没有匹配的订单。",
      configs: "没有匹配的配置。",
      tags: "没有匹配的标签。",
      roles: "没有匹配的角色。",
      permissions: "没有权限数据。",
      banners: "没有匹配的轮播。",
      reports: "没有匹配的举报。",
      decorations: "没有匹配的装饰品。",
      achievements: "没有匹配的成就。",
    },
    status: {
      DRAFT: "草稿",
      PUBLISHED: "已发布",
      PENDING: "待处理",
      PAID: "已支付",
      CANCELLED: "已取消",
      REFUNDED: "已退款",
      PROCESSING: "处理中",
      RESOLVED: "已解决",
      REJECTED: "已拒绝",
      UNDER_REVIEW: "审核中",
      APPROVED: "已通过",
      active: "启用",
      inactive: "停用",
      deleted: "已删除",
      public: "公开",
      private: "私有",
    },
  },
  en: {
    metaTitle: "Admin Dashboard",
    metaDescription:
      "Manage users, articles, comments, orders, configs, and operational modules.",
    shell: {
      eyebrow: "Admin",
      title: "Dashboard",
      description:
        "Manage core site data through the existing SDK with a dedicated back-office shell.",
      accountEntry: "Open front profile",
      noRoleHint:
        "No explicit admin role was detected. If APIs return 403, verify account permissions.",
    },
    common: {
      loading: "Loading dashboard data...",
      reload: "Reload",
      retry: "Retry",
      reset: "Reset",
      search: "Search",
      save: "Save",
      cancel: "Cancel",
      edit: "Edit",
      delete: "Delete",
      deleteConfirm: "Delete this item?",
      audit: "Audit",
      auditConfirm: "Audit this article?",
      approve: "Approve",
      reject: "Reject",
      auditReason: "Audit Reason",
      filters: "Filters",
      queryTable: "Query Table",
      expand: "Expand",
      collapse: "Collapse",
      noFilters: "No filters applied",
      pageSize: "Per page",
      refresh: "Refresh",
      density: "Density",
      columnSetting: "Columns",
      densityDefault: "Default",
      densityMiddle: "Middle",
      densitySmall: "Compact",
      previous: "Previous",
      next: "Next",
      all: "All",
      noData: "No data",
      noPermission:
        "This account may not have back-office permission. Check API authorization.",
      page: "Page {page} / {totalPages}",
      currentPageCount: "{count} items on this page",
    },
    nav: {
      overview: "Overview",
      users: "Users",
      articles: "Articles",
      comments: "Comments",
      orders: "Orders",
      configs: "Configs",
      tags: "Tags",
      roles: "Roles",
      permissions: "Permissions",
      banners: "Banners",
      reports: "Reports",
      decorations: "Decorations",
      achievements: "Achievements",
    },
    pages: {
      overview: {
        title: "Site Overview",
        description:
          "Start with exact counts, then inspect the latest changes across the main management modules.",
      },
      users: {
        title: "User Management",
        description:
          "Review account status, roles, content output, and recent activity.",
      },
      articles: {
        title: "Article Management",
        description:
          "Inspect article status, author ownership, traffic, and recent updates.",
      },
      comments: {
        title: "Comment Management",
        description:
          "Search comment content and trace each record back to its article context.",
      },
      orders: {
        title: "Order Management",
        description:
          "Track payment state, recent transactions, and operational order flow.",
      },
      configs: {
        title: "Config Management",
        description:
          "Review config groups, value types, and public exposure from one place.",
      },
      tags: {
        title: "Tag Management",
        description: "Review tag basics, content volume, and follow heat.",
      },
      roles: {
        title: "Role Management",
        description: "Review role status, system flags, and permission counts.",
      },
      permissions: {
        title: "Permission Management",
        description:
          "Review permission keys and descriptions for the admin boundary.",
      },
      banners: {
        title: "Banner Management",
        description: "Review banner status, target links, and sort order.",
      },
      reports: {
        title: "Report Management",
        description: "Inspect report records and moderation status.",
      },
      decorations: {
        title: "Decoration Management",
        description: "Review decoration status, type, rarity, and pricing.",
      },
      achievements: {
        title: "Achievement Management",
        description:
          "Review achievement basics, type, rarity, and enabled state.",
      },
    },
    summary: {
      users: "Total Users",
      articles: "Total Articles",
      comments: "Total Comments",
      orders: "Total Orders",
      pendingOrders: "Pending Orders",
      configs: "Config Entries",
    },
    sections: {
      latestUsers: "Latest Users",
      latestArticles: "Latest Articles",
      latestComments: "Latest Comments",
      latestOrders: "Latest Orders",
      latestConfigs: "Config Preview",
      recentChanges: "Recent Changes",
      moduleShortcuts: "Modules",
    },
    shortcuts: {
      overview: "See top-level counts and recent changes.",
      users: "Search accounts and inspect role assignments.",
      articles: "Review article status and ownership.",
      comments: "Inspect comment content with article context.",
      orders: "Track payment status and order flow.",
      configs: "Review system configuration entries.",
      tags: "Review tag counts, sorting, and follow heat.",
      roles: "Check role status, system flags, and permission scale.",
      permissions: "Inspect permission points and descriptions.",
      banners: "Review banner status, image, and link settings.",
      reports: "Inspect report records and moderation status.",
      decorations: "Review decoration type, price, and availability.",
      achievements: "Review achievement type, rarity, and enabled state.",
    },
    filters: {
      keyword: "Keyword",
      keywordPlaceholder: "Enter keyword",
      articleTitlePlaceholder: "Enter article title",
      commentPlaceholder: "Search comment content",
      orderPlaceholder: "Search order no. or title",
      configPlaceholder: "Search config key or description",
      tagNamePlaceholder: "Enter tag name",
      roleNamePlaceholder: "Enter role name",
      bannerTitlePlaceholder: "Enter banner title",
      reportPlaceholder: "Search report reason",
      decorationPlaceholder: "Search decoration name",
      achievementPlaceholder: "Search achievement name",
      status: "Status",
      group: "Group",
    },
    columns: {
      user: "User",
      roles: "Roles",
      posts: "Articles",
      followers: "Followers",
      updatedAt: "Updated",
      article: "Article",
      author: "Author",
      category: "Category",
      views: "Views",
      comments: "Comments",
      status: "Status",
      content: "Content",
      sourceArticle: "Article",
      likes: "Likes",
      replies: "Replies",
      orderNo: "Order No.",
      title: "Title",
      type: "Type",
      amount: "Amount",
      userId: "User ID",
      key: "Key",
      value: "Value",
      public: "Public",
      group: "Group",
      name: "Name",
      description: "Description",
      sort: "Sort",
      count: "Count",
      system: "System",
      permissions: "Permissions",
      image: "Image",
      link: "Link",
      action: "Action",
      reason: "Reason",
      categoryLabel: "Category",
      rarity: "Rarity",
      price: "Price",
      enabled: "Enabled",
      code: "Code",
    },
    empty: {
      users: "No matching users.",
      articles: "No matching articles.",
      comments: "No matching comments.",
      orders: "No matching orders.",
      configs: "No matching configs.",
      tags: "No matching tags.",
      roles: "No matching roles.",
      permissions: "No permissions found.",
      banners: "No matching banners.",
      reports: "No matching reports.",
      decorations: "No matching decorations.",
      achievements: "No matching achievements.",
    },
    status: {
      DRAFT: "Draft",
      PUBLISHED: "Published",
      PENDING: "Pending",
      PAID: "Paid",
      CANCELLED: "Cancelled",
      REFUNDED: "Refunded",
      PROCESSING: "Processing",
      RESOLVED: "Resolved",
      REJECTED: "Rejected",
      UNDER_REVIEW: "Under Review",
      APPROVED: "Approved",
      active: "Active",
      inactive: "Inactive",
      deleted: "Deleted",
      public: "Public",
      private: "Private",
    },
  },
} as const;

export function getDashboardCopy(locale?: string) {
  return locale === "en" ? copy.en : copy.zh;
}
